version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo "Entered build phase"
      - cd authorizationService
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t 937883/AuthorisationService .
      - docker tag 937883/AuthorisationService 222512976514.dkr.ecr.us-east-2.amazonaws.com/pracreg:AuthorisationService
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 222512976514.dkr.ecr.us-east-2.amazonaws.com/pracreg:AuthorisationService
   
    - printf '[{"name":"AuthorisationService-container","imageUri":"%s"}]' 222512976514.dkr.ecr.us-east-2.amazonaws.com/pracreg:AuthorisationService > taskdefinition.json
artifacts:
  files:
    - authorizationService/taskdefinition.json