version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo "Entered build phase"
      - cd ClaimMicroservice-2
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t 937883/ClaimsMicroservice .
      - docker tag 937883/ClaimsMicroservice 222512976514.dkr.ecr.us-east-2.amazonaws.com/pracreg:ClaimsMicroservice
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 222512976514.dkr.ecr.us-east-2.amazonaws.com/pracreg:ClaimsMicroservice
   
    - printf '[{"name":"ClaimsMicroservice-container","imageUri":"%s"}]' 222512976514.dkr.ecr.us-east-2.amazonaws.com/pracreg:ClaimsMicroservice > taskdefinition.json
artifacts:
  files:
    - ClaimMicroservice-2/taskdefinition.json